modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="waterbilibili"
version="2.2.0"
displayName="WaterBilibili"
# ğŸ‘‡ è¿™ä¸€è¡ŒæŒ‡å®šå›¾æ ‡ï¼Œæ–‡ä»¶åå¿…é¡»å’Œä½ æ”¾åœ¨ resources æ–‡ä»¶å¤¹é‡Œçš„å›¾ç‰‡ä¸€è‡´
logoFile="logo.png"
description="WaterFrames Addon"
authors="Me"

[[dependencies.waterbilibili]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.waterbilibili]]
modId="waterframes"
type="required"
versionRange="[2.0,)"
ordering="AFTER"
side="BOTH"